# .github/workflows/maven_dispatch.yml (Repo B)
name: Triggered Build from Repo A

on:
  repository_dispatch:
    types: [trigger-build]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run SiteMonitoring.java
        run: |
          mvn compile
          java -cp target/classes com.yourpackage.SiteMonitoring
